command: 'sh -c ''set ; python /code/keras/cifar10/cifar10_cnn.py --owner-id $ML_OWNER_ID --project-token elDDbnrkMZlsqfIc --batch-size 64 --epochs 1000 --processes 200 ; true'''

data_volume: 5669525206859776
data_query: '@version:5e1d20fb211f82df12893a45f3c86328eefaaddd  @sample:0.001 @split:0.84:0.16  @seed:1337'
data_use_iterator: true
#data_dest_folder: '/data/$@/$dir'

image: missinglinkai/tensorflow:nvidia-ec2
#image: missinglinkai/tensorflow:18.01-py2
#git_repo: 'git@github.com:missinglinkai/MissingLink-Demo.git'
#git_tag: 'master'

gpu: true
org: 'missinglinkdemo'
output_paths: ['/output']
project: '5742668902563840'

